news/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('newsposts.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

newsposts/urls.py
from newsposts import views
from django.urls import path, include
from django.contrib import admin

app_name = 'newsposts'
urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.login_news, name='login'),
    path('logout/', views.logout_news, name='logout'),
    path('register/', views.register_news, name="register"),
    path('about/', views.about, name='about'),
    path('news/', views.posts, name='posts'),
    path('news/<int:newspost_id>/', views.post_specific, name='posts_individual'),
    path('news/<int:newspost_id>/comment/', views.post_comment, name='post_comment')

]

newsposts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Newspost(models.Model):
    newspost_title_text = models.CharField(max_length=200)
    newspost_main_text = models.CharField(max_length=200)
    newspost_photo = models.ImageField(upload_to='post_photos/', null=True, blank=True)
    newspost_audio = models.FileField(upload_to='post_audio/', null=True, blank=True)
    newspost_video = models.FileField(upload_to='post_video/', null=True, blank=True)
    pub_date = models.DateTimeField('date published')
    newspost_author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return self.newspost_title_text

class Comment(models.Model):
    newspost_parent = models.ForeignKey(Newspost, on_delete=models.CASCADE)
    comment_parent = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True)
    comment_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    comment_author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    approved_status = models.BooleanField(default=False)

    def __str__(self):
        return self.comment_text

    @property
    def comment_author_name(self):
        """ Intended to easily return author name """
        return self.comment_author.username

newsposts/views.py
from django.shortcuts import render
from django.http import HttpResponse,  Http404, HttpResponseRedirect
from django.shortcuts import get_object_or_404, get_list_or_404
from django.urls import reverse

from .models import Newspost, Comment
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User, Group, Permission
from django.contrib.auth.decorators import login_required, permission_required
from django.utils import timezone
from django.conf import settings

import requests


# Static variables

google_captcha_url = 'https://www.google.com/recaptcha/api/siteverify'
google_captcha_key = settings.CAPTCHA_SERVER_KEY
default_group_name = settings.DEFAULT_GROUP_NAME


# Helper Functions

def make_post_request_json(go_url, data_dict):
    r = requests.post(go_url, data_dict)
    return r.json()


# Views here.

def home(request):
    context = {}
    try:
        context['latest_post_list'] = Newspost.objects.order_by('-pub_date')[:3]
    except:
        pass
    
    return render(request, 'index.html', context)

def about(request):
    context = {}
    try:
        context['admin_list'] = User.objects.filter(is_staff=True)
    except:
        pass

    return render(request, 'about.html', context)

def register_news(request):
    context = {'form_type': "Register"}
    if request.method == 'POST':
        # Validate Captcha and Form
        json = make_post_request_json(google_captcha_url, {'secret': google_captcha_key, 'response':request.POST['g-recaptcha-response'],})
        form_validity = UserCreationForm({'username': request.POST['username'], 'password1': request.POST['password1'], 'password2': request.POST['password2']}).is_valid()
        if json['success'] == True and form_validity:
            u = User.objects.create_user(request.POST['username'], '', request.POST['password1'] )
            try:
                g = Group.objects.get(name=default_group_name)
            except:
                # Group does not exist, create group and add permissions
                g = Group.objects.get_or_create(name=default_group_name)[0]
                p1 = Permission.objects.get(name='Can add comment')
                p2 = Permission.objects.get(name='Can view comment')
                p3 = Permission.objects.get(name='Can view post')
                p4 = Permission.objects.get(name='Can view newspost')
                g.permissions.set([p1, p2, p3, p4])
                context['error_message'] = "Your account may need further validation before full access"
            # Add resulting group to the user
            u.groups.add(g)
            print(u.groups)
        else:
            # Captcha or form validation failed
            context['error_message'] = "There was an issue with your request"
    # Return form with resulting error messages in context if any
    context['form'] = UserCreationForm()
    return render(request, 'registration/login.html', context)

def login_news(request):
    context = {'form_type': "Log In"}
    if request.method == 'POST':
        # Validate Captcha and Form
        json = make_post_request_json(google_captcha_url, {'secret': google_captcha_key, 'response':request.POST['g-recaptcha-response'],})
        if json['success'] == True:
            # I don't like this, data is pulled straight from post request
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(request, username=username, password=password)                
            if user is not None:
                login(request, user)
                # Redirect to a success page.
                return HttpResponseRedirect(reverse('newsposts:home'))
            else:
                # Return an 'invalid login' error message.
                context['error_message'] = 'Incorrect Username or Password'
        else:
            # This case if there is an issue with the robot check or form
            context['error_message'] = 'Issue with your request'
    context['form'] = AuthenticationForm()
    return render(request, 'registration/login.html', context)

def logout_news(request):
    # Log out user if they are logged in. Otherwiser redirect to home
    if request.user.is_authenticated:
        logout(request)
    
    return HttpResponseRedirect(reverse('newsposts:home')) 

@login_required
@permission_required('newsposts.view_newspost', raise_exception=True)
def posts(request):
    # Return a list of posts
    latest_post_list = get_list_or_404(Newspost.objects.order_by('-pub_date'))[:10]
    context = {'latest_post_list': latest_post_list}
    return render(request, 'newsposts.html', context)

@login_required
@permission_required('newsposts.view_newspost', raise_exception=True)
def post_specific(request, newspost_id):
    # View a specific post
    newspost = get_object_or_404(Newspost, pk=newspost_id)
    comment_list = list(newspost.comment_set.filter(approved_status=True).values())
    # Load comment Author objects for complete information
    for c in comment_list:
        c['comment_author_name'] = User.objects.get(pk=c['comment_author_id']).username
    context = {'p': newspost, 'comment_list': comment_list}
    return render(request, 'newspost_individual.html', context)

@login_required
@permission_required('newsposts.add_comment', raise_exception=True)
def post_comment(request, newspost_id):
    # Post a comment to a post
    if request.method == 'POST' and request.user.is_authenticated:
        # Verify Captcha
        json = make_post_request_json(google_captcha_url, {'secret': google_captcha_key, 'response':request.POST['g-recaptcha-response']})
        if json['success'] == True:
            newspost = get_object_or_404(Newspost, pk=newspost_id)
            comment = Comment(newspost_parent=newspost, comment_text=request.POST['comment_text'], pub_date=timezone.now(), comment_author=request.user)
            comment.save()
        
    return HttpResponseRedirect(reverse('newsposts:posts_individual', args=(newspost_id,)))

newsposts/templates/about.html
{% extends 'wrapper.html' %}

{% block content %}
{% if admin_list %}
<div class="grid-container">
    {% for a in admin_list %}
    <div class="cell medium-8">
        <div class="card">
            <div class="card-section">
                <h1>{{ a.username }}</h1>
            </div>
            <div class="card-section">
                <p>Lorem ipSum</p>
            </div>
        </div>
    </div>    
    {% endfor %}
</div>
{% endif %}
{% endblock %}

newsposts/templates/index.html
{% extends 'wrapper.html' %}
{% block content %}
<div class="callout large primary hero">
    <div class="row column text-center">
      <h1>Title</h1>
      <h4 class="subheader">Subtitle</h4>
    </div>
</div>
<div class="post_list">
{% if latest_post_list %}
<article class="grid-container">
  {% for p in latest_post_list %}
    <div class="grid-x align-center">
      <div class="cell medium-8">
        <div class="blog-post">
            
          <h3>{{ p.newspost_title_text }} </h3>
          <h5>By <a href="{% url 'newsposts:about' %}">{{ p.newspost_author }} </a><small>{{ p.pub_date }}</small></h5>        
                
          <!--Load Video if available-->
          {% if p.newspost_video %}
          <div class="media-object">
            <video controls>
              <source src="{{ MEDIA_URL }}{{ p.newspost_video }}">
            </video>
          </div>
          {% endif %}

          <!--Load Audio if avaibale-->
          {% if p.newspost_audio %}
          <div class="media-object">
            <audio controls>
              <source src="{{ MEDIA_URL }}{{ p.newspost_audio }}">
            </audio>
          </div>
          {% endif %}
              
          <!--Load Thumbnail if available-->
          {% if p.newspost_photo and not p.newspost_video %}
          <div class="media-object">
              <img src="{{ MEDIA_URL }}{{ p.newspost_photo }}">
          </div>
          {% endif %}

          <!--Attributes of post section-->
          <div class="callout">
            <p>{{ p.newspost_main_text }}</p>
            <a class="more-link" href="{% url 'newsposts:posts_individual' p.id %}">More...</a>
          </div>

        </div>
      </div>
    </div>
  {% endfor %}
</article>
{% else %}
    <p>No posts are available.</p>
{% endif %}
</div>
{% endblock %}

newsposts/templates/newspost_individual.html
{% extends 'wrapper.html' %}

{% block content %}
    {% if p %}
    <article class="grid-container solo-dolo">
        <div class="grid-x align-center">
            <div class="cell medium-8">
              <div class="blog-post">
                  
                <h3>{{ p.newspost_title_text }} </h3>
                <h5>By <a href="{% url 'newsposts:about' %}">{{ p.newspost_author }} </a><small>{{ p.pub_date }}</small></h5>            
              <!--Load Video if avaibale-->
                {% if p.newspost_video %}
                <div class="media-object">
                  <video controls>
                    <source src="{{ MEDIA_URL }}{{ p.newspost_video }}">
                  </video>
                </div>
                {% endif %}

              <!--Load Audio if avaibale-->
                {% if p.newspost_audio %}
                <div class="media-object">
                  <audio controls>
                    <source src="{{ MEDIA_URL }}{{ p.newspost_audio }}">
                  </audio>
                </div>
                {% endif %}
              
              <!--Load Thumbnail if available-->
              {% if p.newspost_photo and not p.newspost_video %}
                <div class="media-object">
                  <img src="{{ MEDIA_URL }}{{ p.newspost_photo }}">
                </div>
              {% endif %}
      
              <!--Attributes of post section-->
                <div class="callout">
                  <p>{{ p.newspost_main_text }}</p>
                </div>
              
              
              </div>
            </div>
          </div>
          <div class="grid-x align-center">
            <div class="cell medium-8">
              {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
              {% if user.is_authenticated %}
              Commenting as {{ user.username }}
              <form action="{% url 'newsposts:post_comment' p.id %}" method="post">
              <script src="https://www.google.com/recaptcha/api.js" async defer></script>
              {% csrf_token %}
              <input type="text" id="comment_post_text" name="comment_text" placeholder="Enter comment here...">
              <div class="g-recaptcha" data-sitekey="{{ CAPTCHA_SITE_KEY }}"></div>
              <br/>
              <input type="submit">
              </form>
              {% else %}
                <p><a href="{% url 'login' %}">Please sign in to comment...</a></p>
              {% endif %}
            </div>
          </div>
        </br>
          <div class="grid-x align-center">
            {% if comment_list %}
              {% for c in comment_list %}
              <div class="cell medium-8">
                  <h5>{{ c.comment_author_name }} <small>{{ c.pub_date }}</small></h5>
                  <p>{{ c.comment_text }}</p>
              </div>
              {% endfor %}
            {% else %}
            <h1>No Comments yet...</h1>
            {% endif %}
          </div>  
    </article>
    {% endif %}
{% endblock %}

newsposts/templates/newsposts.html
{% extends 'wrapper.html' %}
{% block content %}
    <div class="post_list">
    {% if latest_post_list %}
      <article class="grid-container solo-dolo">  
        {% for p in latest_post_list %}  
          <div class="grid-x align-center">
            <div class="cell medium-8">
              <div class="blog-post">
                  
                <h3>{{ p.newspost_title_text }} </h3>
                <h5>By <a href="{% url 'newsposts:about' %}">{{ p.newspost_author }} </a><small>{{ p.pub_date }}</small></h5>           
                      
                <!--Load Video if available-->
                {% if p.newspost_video %}
                <div class="media-object">
                  <video controls>
                    <source src="{{ MEDIA_URL }}{{ p.newspost_video }}">
                  </video>
                </div>
                {% endif %}

                <!--Load Audio if avaibale-->
                {% if p.newspost_audio %}
                <div class="media-object">
                  <audio controls>
                    <source src="{{ MEDIA_URL }}{{ p.newspost_audio }}">
                  </audio>
                </div>
                {% endif %}
              
                <!--Load Thumbnail if available-->
                {% if p.newspost_photo and not p.newspost_video %}
                <div class="media-object">
                  <img src="{{ MEDIA_URL }}{{ p.newspost_photo }}">
                </div>
                {% endif %}

                <!--Attributes of post section-->
                <div class="callout">
                  <p>{{ p.newspost_main_text }}</p>
                  <a class="more-link" href="{% url 'newsposts:posts_individual' p.id %}">More...</a>
                </div>
                
              </div>
            </div>
          </div>
        {% endfor %}
      </article>
    {% else %}
        <p>No posts are available.</p>
    {% endif %}
    </div>
{% endblock %}

newsposts/templates/wrapper.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Vagrants | Welcome</title>
    <!-- Compressed CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/foundation-sites@6.6.3/dist/css/foundation.min.css" integrity="sha256-ogmFxjqiTMnZhxCqVmcqTvjfe1Y/ec4WaRj/aQPvn+I=" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
    <!-- Compressed JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/foundation-sites@6.6.3/dist/js/foundation.min.js" integrity="sha256-pRF3zifJRA9jXGv++b06qwtSqX1byFQOLjqa2PTEb2o=" crossorigin="anonymous"></script>
    {% load static %}
    <link rel="stylesheet" href="{% static 'newsposts/custom.css' %}">
  </head>
  <body>

    <!-- Start Top Bar -->
    <div class="top-bar sticky">
      <div class="top-bar-left">
        <ul class="menu">
          <li class="menu-text">Podcast/Show</li>
          <li><a href="{% url 'newsposts:home' %}">Home</a></li>
          <li><a href="{% url 'newsposts:posts' %}">List</a></li>
          <li><a href="{% url 'newsposts:about' %}">About</a></li>
        </ul>
      </div>
      <div class="top-bar-right">
        <ul class="menu">
          {% if user.is_authenticated %}
          <li class="menu-text algin-right">Hi {{ user.username }}!</li>
          <li class="align-right"><a href="{% url 'newsposts:logout' %}"> Log Out</a></li>
          {% else %}
          <li class="menu-text align-right">Hi Stranger!!</li>
          <li class="align-right"><a href="{% url 'newsposts:login' %}">Log In</a></li>
          {% endif %}
        </ul>
      </div>
    </div>
    <!-- End Top Bar -->
    {% block content %}
    {% endblock %}
    <script>
        $(document).foundation();
    </script>
</body>
</html>